FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    software-properties-common \
    build-essential \
    wget \
    curl \
    git
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.11 python3.11-dev python3.11-venv lsof

RUN curl -fsSL https://ollama.com/install.sh | sh

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1

RUN python3 --version

RUN apt-get install -y nvidia-utils-550

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py

# 安装 langchain-chatchat 并更新到最新版本

RUN pip install pyyaml
RUN pip install langchain-chatchat -U
RUN pip install opencv-python-headless 
RUN pip show opencv-python-headless && pip uninstall -y opencv-python-headless || true
RUN pip install python-dotenv
RUN pip install Flask requests


# 安装 Ollama


WORKDIR /app

RUN chatchat init

RUN rm -r /app/data/knowledge_base/samples/content
RUN mkdir /app/data/knowledge_base/samples/content


EXPOSE 7861
