FROM base:latest

ARG Folder
ARG Model
ARG Topic
ARG InternalIP
ARG Port
ARG ControlPort

ENV My_Model=${Model}
ENV My_Topic=${Topic}
ENV My_IP=${InternalIP}
ENV My_Port=${Port}
ENV My_ControlPort=${ControlPort}

RUN echo "The folder is ${Folder}."
RUN echo "The model is ${Model}."
RUN echo "The topic is ${Topic}."
RUN echo "The internal IP is ${InternalIP}."
RUN echo "The port is ${Port}."
RUN echo "The control port is ${ControlPort}."


WORKDIR /app

COPY ./startS.sh /app
COPY ./langchain/kb_settings.yaml /app/
COPY ./langchain/model_settings.yaml /app/
COPY ./langchain/prompt_settings.yaml /app/
COPY ./langchain/tool_settings.yaml /app/
COPY ./server/changeModel.py /app/
COPY ./server/server_compute.py /app/
RUN rm -rf /app/data/knowledge_base/samples/content/*
COPY ./data/${Folder}/* /app/data/knowledge_base/samples/content/
COPY ./models/${Model}/* /root/.ollama

CMD ["/app/startS.sh"]

